# Generated by Django 3.2.16 on 2022-12-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('article', 'Article'), ('category', 'Category'), ('recipe', 'Recipe')], default='Recipe', max_length=100),
        ),
    ]
