# Generated by Django 3.2.16 on 2022-11-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_maker', '0002_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'beginner'), ('Medium', 'medium'), ('Advanced', 'advanced')], default='Beginner', max_length=100),
        ),
    ]
