# Generated by Django 3.2.16 on 2022-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_maker', '0005_auto_20221205_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
